service: clau-platform

provider:
  name: aws
  stage: prod
  runtime: nodejs18.x

package:
  patterns:
    - "!**"
    - ".output/**"
    - ".env"

functions:
  api:
    handler: .output/server/index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline