name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        description: "Select environment"
        required: true
        default: "prod"
        type: choice
        options:
          - prod

run-name: Deploy to '${{ github.ref == 'refs/heads/main' && inputs.stage || 'prod' }}' commit '${{ github.sha }}'

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_OPTIONS: "--max_old_space_size=4096"
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy 
    
    steps:
      - name: Checkout code 📁
        uses: actions/checkout@v3
      
      - name: Add npm credentials 🔒
        run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
    
      - name: Install Deno ⬇️
        uses: denoland/setup-deno@v1
        with: 
          deno-version: v1.x

      - name: Install dependencies ⬇️
        run: npm ci

      - name: Install deployctl ⬇️
        run: deno install -A -r -f https://deno.land/x/deploy/deployctl.ts

      - name: Install serverless CLI ⬇️
        run: npm i -g serverless

      - name: Setup AWS keys
        run: serverless config credentials --provider aws --key ${{ secrets.CLAU_AWS_KEY }} --secret ${{ secrets.CLAU_AWS_SECRET }}

      - name: Build - AWS Lambda ⚒️
        run: npm run build:aws-lambda
      
      - name: Deploy - AWS Lambda 🚀
        run: npm run deploy:aws-lambda

      - name: Build - Deno ⚒️
        run: npm run build:deno
      
      - name: Deploy - Deno 🚀
        run: npm run deploy:deno